Feature hu01
jchernandezUA/vinylOS-ua pull request #49
Opened 2024-11-02 04:45 UTC by jflorez91

Se agrega funcionalidad dela HU01 - Listar Albumes.

2024-11-02 13:57 UTC, aanieves approved these changes

2024-11-02 14:08 UTC, nicoGarciaValde approved these changes

2024-11-02 18:05 UTC, jchernandezUA requested changes

2024-11-02 18:05 UTC, jchernandezUA commented on app/src/main/AndroidManifest.xml
> +        <activity
esto no debe ir aquí no se declaran screens como si fueran activities

2024-11-03 14:54 UTC, jchernandezUA approved these changes

2024-11-03 14:54 UTC, merged